"""A3 — proof that the tenant boundary is enforced by PostgreSQL, not by us.

Why this file needs a scratch database
--------------------------------------
Proving isolation requires a second tenant with real rows in `samples`,
`classes` and `raw_uploads`. Writing those into the live database is not
acceptable here: a Celery beat reconciles active Postgres rows back into
`dataset/samples.csv` every five minutes, so test fixtures could be copied into
the source of truth and would then need a fresh signed SOT version to remove.

So the proof runs against a database created for the run and dropped after it,
built from the REAL production DDL (`metadata_db.DDL_STATEMENTS`) and the REAL
policy SQL (`rls.rls_ddl()`). Nothing here re-implements the schema or the
policy; if either changes, this suite exercises the new one.

Why it connects as `voya_app` and not `admin`
---------------------------------------------
Superusers bypass row security unconditionally. Run as `admin`, every assertion
below would pass for the wrong reason — the rows would be visible and the
"isolation" would be the test's own WHERE clauses. The suite skips rather than
lies when the contained role is unavailable.

What the app layer contributes
------------------------------
The scope SQL executed here is generated by `rls.scope_parameters()` and
`rls._APPLY_SCOPE_SQL`, the same two things `rls.apply_scope()` uses in
production. `TestApplicationLayerEmitsScope` closes the loop by asserting that
the two functions every metadata query passes through do call `apply_scope`.
"""

from __future__ import annotations

import os
import uuid

import psycopg2
import pytest
from urllib.parse import urlsplit, urlunsplit

from app.storage import rls

TENANT_A = "proof-a"
TENANT_B = "proof-b"

# Hex-10, because `samples_uid_is_hex10` is a live CHECK constraint.
SAMPLE_A = "aaaaaaaa01"
SAMPLE_B = "bbbbbbbb01"


# ---------------------------------------------------------------------------
# Scratch database
# ---------------------------------------------------------------------------


def _admin_dsn() -> str:
    from app.config import settings
    from app.storage.postgres_connection import migration_dsn

    return migration_dsn() or settings.database_url


def _with_database(dsn: str, dbname: str) -> str:
    parts = urlsplit(dsn)
    return urlunsplit((parts.scheme, parts.netloc, f"/{dbname}", "", ""))


def _with_user(dsn: str, user: str, password: str) -> str:
    from urllib.parse import quote

    parts = urlsplit(dsn)
    host = parts.hostname or "postgres"
    netloc = f"{user}:{quote(password, safe='')}@{host}"
    if parts.port:
        netloc += f":{parts.port}"
    return urlunsplit((parts.scheme, netloc, parts.path, "", ""))


def _app_password() -> str:
    """Password for the contained role, from the environment or the repo .env.

    Read lazily rather than in conftest: only this suite needs it, and a
    deployment that has not provisioned the role should skip rather than fail.
    """
    password = os.getenv("VOYA_APP_DB_PASSWORD", "").strip()
    if password:
        return password
    from pathlib import Path

    envf = Path(__file__).resolve().parents[2] / ".env"
    if envf.exists():
        for line in envf.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line.startswith("VOYA_APP_DB_PASSWORD=") and not line.startswith("#"):
                return line.split("=", 1)[1].strip()
    return ""


@pytest.fixture(scope="module")
def scratch_db():
    """A throwaway database carrying the real schema and the real policies."""
    from app.cli.provision_db_roles import APP_ROLE, provision
    # `AUTHZ_DDL_STATEMENTS` phải có mặt, và nó không phải tuỳ chọn: từ PDM
    # v1.0, `rls.rls_ddl()` cài chính sách cho cả tám bảng của mặt phẳng phân
    # quyền. Dựng schema mà thiếu chúng thì vòng lặp `rls_ddl()` bên dưới —
    # vòng lặp CỐ Ý không nuốt lỗi, vì nó chính là thứ đang được kiểm — sẽ
    # chết với `relation "workspaces" does not exist`.
    from app.storage.authz_schema import AUTHZ_DDL_STATEMENTS
    from app.storage.metadata_db import DDL_STATEMENTS, MIGRATION_STATEMENTS

    password = _app_password()
    if not password:
        pytest.skip("VOYA_APP_DB_PASSWORD not set — run app.cli.provision_db_roles first")

    admin_dsn = _admin_dsn()
    dbname = f"voya_rls_proof_{uuid.uuid4().hex[:8]}"

    try:
        bootstrap = psycopg2.connect(admin_dsn, connect_timeout=5)
    except Exception as exc:  # pragma: no cover - environment dependent
        pytest.skip(f"no live Postgres: {exc}")

    bootstrap.autocommit = True
    with bootstrap.cursor() as cur:
        cur.execute(f'CREATE DATABASE "{dbname}"')
    bootstrap.close()

    scratch_admin = _with_database(admin_dsn, dbname)
    scratch_app = _with_user(scratch_admin, APP_ROLE, password)

    try:
        conn = psycopg2.connect(scratch_admin, connect_timeout=5)
        conn.autocommit = True
        with conn.cursor() as cur:
            # Same tolerance as ensure_tables(): statements are idempotent and a
            # failure of one must not abort the rest.
            for stmt in (list(DDL_STATEMENTS) + list(MIGRATION_STATEMENTS)
                         + list(AUTHZ_DDL_STATEMENTS)):
                try:
                    cur.execute(stmt)
                except Exception:
                    pass
            for stmt in rls.rls_ddl():
                cur.execute(stmt)  # these must NOT fail — they are the subject
        # Table privileges are per-database, so the role provisioned against the
        # live database has none here until this runs.
        provision(conn, password)
        _seed(conn)
        conn.close()

        yield scratch_app
    finally:
        drop = psycopg2.connect(admin_dsn, connect_timeout=5)
        drop.autocommit = True
        with drop.cursor() as cur:
            cur.execute(
                "SELECT pg_terminate_backend(pid) FROM pg_stat_activity "
                "WHERE datname = %s AND pid <> pg_backend_pid()",
                (dbname,),
            )
            cur.execute(f'DROP DATABASE IF EXISTS "{dbname}"')
        drop.close()


def _seed(conn) -> None:
    """One class, one sample and one raw upload for each of two tenants.

    `dialect` is left NULL on purpose: the composite foreign key
    `(tenant_id, dialect) -> dialects` is MATCH SIMPLE, so a NULL member leaves
    it unenforced and the fixture does not have to clone a whole vocabulary
    registry to prove a row-visibility property.
    """
    with conn.cursor() as cur:
        # Gieo dữ liệu cho HAI tenant, nên phải ở phạm vi hệ thống — đúng thứ
        # `rls.py` định nghĩa cho việc nền tảng làm xuyên tenant.
        #
        # Trước đây dòng này không cần, và đó mới là điều đáng nói: fixture chạy
        # bằng `admin`, một superuser, nên nó MIỄN TRỪ khỏi RLS và phần gieo dữ
        # liệu chưa bao giờ đi qua chính sách. Khi lượt chạy đổi sang vai chủ sở
        # hữu thường, `FORCE ROW LEVEL SECURITY` lập tức chặn — tức chính sách
        # vẫn đúng, chỉ là bộ kiểm đã đứng ngoài nó suốt.
        #
        # `SET` chứ không `SET LOCAL`: kết nối này đang autocommit, không có
        # giao dịch nào để `LOCAL` bám vào.
        cur.execute(f"SET {rls.SYSTEM_SCOPE_GUC} = '{rls.SYSTEM_SCOPE_ON}'")
        for tenant in (TENANT_A, TENANT_B):
            cur.execute(
                "INSERT INTO tenants(tenant_id, display_name, slug) VALUES (%s, %s, %s) "
                "ON CONFLICT (tenant_id) DO NOTHING",
                (tenant, tenant, tenant),
            )
        for tenant, sample_uid in ((TENANT_A, SAMPLE_A), (TENANT_B, SAMPLE_B)):
            cur.execute(
                "INSERT INTO classes(class_uid, tenant_id, slug, language) "
                "VALUES (%s, %s, %s, 'vn')",
                (f"cls-{tenant}", tenant, f"slug-{tenant}"),
            )
            cur.execute(
                "INSERT INTO samples(sample_uid, tenant_id, class_uid) VALUES (%s, %s, %s)",
                (sample_uid, tenant, f"cls-{tenant}"),
            )
            cur.execute(
                "INSERT INTO raw_uploads(upload_uid, tenant_id) VALUES (%s, %s)",
                (f"upl-{tenant}", tenant),
            )


@pytest.fixture
def app_conn(scratch_db):
    """A connection authenticated as the contained application role."""
    conn = psycopg2.connect(scratch_db, connect_timeout=5)
    try:
        with conn.cursor() as cur:
            cur.execute(
                "SELECT rolsuper OR rolbypassrls FROM pg_roles WHERE rolname = current_user"
            )
            if cur.fetchone()[0]:  # pragma: no cover - would invalidate the suite
                pytest.fail(
                    "the proof connection can bypass RLS; every assertion below "
                    "would pass for the wrong reason"
                )
        yield conn
    finally:
        conn.rollback()
        conn.close()


def _scoped(conn, tenant=None, system=False):
    """Open a transaction bound to a scope, using the production scope SQL."""
    cur = conn.cursor()
    cur.execute(rls._APPLY_SCOPE_SQL, rls.scope_parameters(tenant, system))
    return cur


# ---------------------------------------------------------------------------
# Read isolation
# ---------------------------------------------------------------------------


class TestReadIsolation:
    @pytest.mark.parametrize("table,key", [
        ("samples", "sample_uid"),
        ("classes", "class_uid"),
        ("raw_uploads", "upload_uid"),
    ])
    def test_a_sees_only_its_own_rows(self, app_conn, table, key):
        cur = _scoped(app_conn, TENANT_A)
        cur.execute(f"SELECT {key}, tenant_id FROM {table}")
        rows = cur.fetchall()
        assert rows, f"{table}: tenant A must see its own row"
        assert {r[1] for r in rows} == {TENANT_A}
        app_conn.rollback()

    def test_b_sees_only_its_own_rows(self, app_conn):
        cur = _scoped(app_conn, TENANT_B)
        cur.execute("SELECT sample_uid FROM samples")
        assert [r[0] for r in cur.fetchall()] == [SAMPLE_B]
        app_conn.rollback()

    def test_targeting_another_tenant_by_primary_key_returns_nothing(self, app_conn):
        """Not merely filtered — invisible. Knowing the id does not help."""
        cur = _scoped(app_conn, TENANT_A)
        cur.execute("SELECT sample_uid FROM samples WHERE sample_uid = %s", (SAMPLE_B,))
        assert cur.fetchone() is None
        app_conn.rollback()

    def test_aggregates_do_not_leak_counts(self, app_conn):
        """COUNT(*) is a read too — a leaked total is a leaked fact."""
        cur = _scoped(app_conn, TENANT_A)
        cur.execute("SELECT count(*) FROM samples")
        assert cur.fetchone()[0] == 1
        app_conn.rollback()

    def test_system_scope_sees_every_tenant(self, app_conn):
        cur = _scoped(app_conn, system=True)
        cur.execute("SELECT tenant_id FROM samples ORDER BY tenant_id")
        assert [r[0] for r in cur.fetchall()] == [TENANT_A, TENANT_B]
        app_conn.rollback()


# ---------------------------------------------------------------------------
# Fail closed — the property that makes a forgotten scope safe
# ---------------------------------------------------------------------------


class TestFailsClosed:
    @pytest.mark.parametrize("table", ["samples", "classes", "raw_uploads"])
    def test_unscoped_connection_reads_nothing(self, app_conn, table):
        """The central claim. An unscoped connection must see zero rows, not all
        rows: a code path someone forgot to scope then returns nothing and gets
        noticed, instead of returning everything and not getting noticed."""
        cur = _scoped(app_conn, None, False)
        cur.execute(f"SELECT count(*) FROM {table}")
        assert cur.fetchone()[0] == 0
        app_conn.rollback()

    def test_connection_that_never_set_the_guc_at_all_reads_nothing(self, app_conn):
        """Distinct from the case above: here no `set_config` runs, so the GUC is
        genuinely undefined rather than empty. `current_setting(x, true)` returns
        NULL, and NULL is not TRUE — which is why the missing_ok form is used."""
        with app_conn.cursor() as cur:
            cur.execute("SELECT count(*) FROM samples")
            assert cur.fetchone()[0] == 0
        app_conn.rollback()

    def test_unscoped_insert_is_rejected(self, app_conn):
        with pytest.raises(psycopg2.errors.InsufficientPrivilege):
            cur = _scoped(app_conn, None, False)
            cur.execute(
                "INSERT INTO samples(sample_uid, tenant_id) VALUES ('cccccccc01', %s)",
                (TENANT_A,),
            )
        app_conn.rollback()

    def test_empty_tenant_id_is_not_a_wildcard(self, app_conn):
        """`''` must behave as "no tenant", not as "match anything"."""
        cur = _scoped(app_conn, "", False)
        cur.execute("SELECT count(*) FROM samples")
        assert cur.fetchone()[0] == 0
        app_conn.rollback()

    def test_system_scope_must_be_exactly_on(self, app_conn):
        """Any other truthy-looking value must not open the gate."""
        for value in ("ON", "true", "1", "yes", " on"):
            cur = app_conn.cursor()
            cur.execute(
                rls._APPLY_SCOPE_SQL,
                (rls.SYSTEM_SCOPE_GUC, value, rls.TENANT_GUC, ""),
            )
            cur.execute("SELECT count(*) FROM samples")
            assert cur.fetchone()[0] == 0, f"{value!r} must not grant system scope"
            app_conn.rollback()


# ---------------------------------------------------------------------------
# Write isolation
# ---------------------------------------------------------------------------


class TestWriteIsolation:
    def test_update_across_tenants_changes_nothing(self, app_conn):
        """The unfiltered UPDATE is the point: `update_sample_gdrive_url()` and
        `delete_sample()` in metadata_db carry no tenant filter to this day. The
        policy is what makes those safe without editing every one of them."""
        cur = _scoped(app_conn, TENANT_A)
        cur.execute("UPDATE samples SET storage_url = 'x' WHERE sample_uid = %s", (SAMPLE_B,))
        assert cur.rowcount == 0
        app_conn.commit()

        check = _scoped(app_conn, TENANT_B)
        check.execute("SELECT storage_url FROM samples WHERE sample_uid = %s", (SAMPLE_B,))
        assert check.fetchone()[0] is None
        app_conn.rollback()

    def test_delete_across_tenants_removes_nothing(self, app_conn):
        cur = _scoped(app_conn, TENANT_A)
        cur.execute("DELETE FROM samples WHERE sample_uid = %s", (SAMPLE_B,))
        assert cur.rowcount == 0
        app_conn.commit()

        check = _scoped(app_conn, TENANT_B)
        check.execute("SELECT count(*) FROM samples WHERE sample_uid = %s", (SAMPLE_B,))
        assert check.fetchone()[0] == 1
        app_conn.rollback()

    def test_blanket_delete_only_empties_the_current_tenant(self, app_conn):
        """A `DELETE FROM samples` with no WHERE at all — the worst plausible
        accident — must not be able to reach another tenant's rows."""
        cur = _scoped(app_conn, TENANT_A)
        cur.execute("DELETE FROM samples")
        assert cur.rowcount == 1
        app_conn.rollback()  # keep the fixture intact for later tests

    def test_cannot_insert_a_row_owned_by_another_tenant(self, app_conn):
        """WITH CHECK. Without it a tenant could write rows into another tenant's
        partition — invisible to itself afterwards, and undetectable from here."""
        with pytest.raises(psycopg2.errors.InsufficientPrivilege):
            cur = _scoped(app_conn, TENANT_A)
            cur.execute(
                "INSERT INTO samples(sample_uid, tenant_id) VALUES ('dddddddd01', %s)",
                (TENANT_B,),
            )
        app_conn.rollback()

    def test_cannot_move_a_row_to_another_tenant(self, app_conn):
        """UPDATE is checked by both clauses: USING picks the row, WITH CHECK
        vets the result. Equal predicates are what close this."""
        with pytest.raises(psycopg2.errors.InsufficientPrivilege):
            cur = _scoped(app_conn, TENANT_A)
            cur.execute(
                "UPDATE samples SET tenant_id = %s WHERE sample_uid = %s",
                (TENANT_B, SAMPLE_A),
            )
        app_conn.rollback()

    def test_insert_into_own_tenant_still_works(self, app_conn):
        """Negative control. If the policy rejected everything the tests above
        would all pass while the application was completely broken."""
        cur = _scoped(app_conn, TENANT_A)
        cur.execute(
            "INSERT INTO samples(sample_uid, tenant_id) VALUES ('eeeeeeee01', %s)",
            (TENANT_A,),
        )
        assert cur.rowcount == 1
        app_conn.rollback()


# ---------------------------------------------------------------------------
# The role itself
# ---------------------------------------------------------------------------


class TestContainedRole:
    def test_cannot_disable_the_policy(self, app_conn):
        """The guarantee must not be self-revocable: if the application role
        could run this statement, every assertion above would be advisory."""
        with pytest.raises(psycopg2.errors.InsufficientPrivilege):
            with app_conn.cursor() as cur:
                cur.execute("ALTER TABLE samples DISABLE ROW LEVEL SECURITY")
        app_conn.rollback()

    def test_cannot_drop_the_policy(self, app_conn):
        with pytest.raises(psycopg2.errors.InsufficientPrivilege):
            with app_conn.cursor() as cur:
                cur.execute(f"DROP POLICY {rls.POLICY_NAME} ON samples")
        app_conn.rollback()

    def test_cannot_create_tables(self, app_conn):
        """A new table would arrive with no policy on it."""
        with pytest.raises(psycopg2.errors.InsufficientPrivilege):
            with app_conn.cursor() as cur:
                cur.execute("CREATE TABLE escape_hatch (id int)")
        app_conn.rollback()


# ---------------------------------------------------------------------------
# The application layer actually emits that scope
# ---------------------------------------------------------------------------


class _RecordingCursor:
    def __init__(self):
        self.calls = []

    def execute(self, sql, params=None):
        self.calls.append((sql, params))


class TestApplicationLayerEmitsScope:
    def test_apply_scope_reads_the_ambient_context(self):
        from app.tenant_context import system_scope, tenant_scope

        cur = _RecordingCursor()
        with tenant_scope("truong-b"):
            rls.apply_scope(cur)
        assert cur.calls[-1][1] == (rls.SYSTEM_SCOPE_GUC, "", rls.TENANT_GUC, "truong-b")

        with system_scope("test"):
            rls.apply_scope(cur)
        assert cur.calls[-1][1] == (
            rls.SYSTEM_SCOPE_GUC, rls.SYSTEM_SCOPE_ON, rls.TENANT_GUC, "",
        )

    def test_scope_sql_is_transaction_local(self):
        """`SET LOCAL` semantics, not `SET`. A plain SET persists on a pooled
        connection and leaks one tenant's context into the next request that
        borrows it — a defect that produces no error at all, just wrong data for
        one user."""
        assert rls._APPLY_SCOPE_SQL.count("true") == 2
        assert "set_config" in rls._APPLY_SCOPE_SQL

    @pytest.mark.parametrize("function", ["_cursor", "_fetch_all"])
    def test_every_metadata_query_binds_a_scope(self, function, monkeypatch):
        """Both database entry points must call apply_scope before anything else.

        Asserted by observing the call, not by reading the source: an assertion
        on source text passes whenever the words appear, including inside the
        comment that explains them.
        """
        import app.storage.metadata_db as mdb

        seen = []
        monkeypatch.setattr(mdb, "apply_scope", lambda cur: seen.append(cur))

        if function == "_cursor":
            with mdb._cursor() as cur:
                cur.execute("SELECT 1")
        else:
            mdb._fetch_all("SELECT 1 AS one")

        assert len(seen) == 1, f"{function} did not bind a tenant scope"


# ---------------------------------------------------------------------------
# Where a request's tenant comes from
# ---------------------------------------------------------------------------


class TestRequestTenantResolution:
    """`tenant_middleware.resolve_tenant` — scope, never access.

    This function decides which tenant's rows a request may touch. It must never
    decide whether the request is authenticated: that stays with the route's own
    dependency, so adding tenant scoping cannot change any endpoint's 401
    behaviour.
    """

    def test_authenticated_user_gets_their_own_tenant(self, monkeypatch):
        import app.tenant_middleware as tm

        monkeypatch.setattr(tm, "_tenant_of_user", lambda uid: "truong-b")
        monkeypatch.setattr("app.auth._subject_of", lambda token: "user-1")
        assert tm.resolve_tenant("cookie-token", None) == "truong-b"

    def test_cookie_wins_over_bearer(self, monkeypatch):
        """Same precedence as get_current_user_optional. A browser migrated from
        the old localStorage flow can still send a stale Bearer header on every
        request; preferring it would scope the session to the wrong tenant."""
        import app.tenant_middleware as tm

        seen = []
        monkeypatch.setattr("app.auth._subject_of", lambda token: seen.append(token) or "u")
        monkeypatch.setattr(tm, "_tenant_of_user", lambda uid: "truong-b")
        tm.resolve_tenant("from-cookie", "from-bearer")
        assert seen == ["from-cookie"]

    def test_anonymous_gets_the_public_tenant(self, monkeypatch):
        import app.tenant_middleware as tm
        from app.config import settings

        monkeypatch.setattr(settings, "public_tenant_id", "default", raising=False)
        assert tm.resolve_tenant(None, None) == "default"

    def test_empty_public_tenant_leaves_anonymous_unscoped(self, monkeypatch):
        """The setting for a deployment with no public catalogue: an anonymous
        caller then sees nothing rather than one tenant's rows."""
        import app.tenant_middleware as tm
        from app.config import settings

        monkeypatch.setattr(settings, "public_tenant_id", "", raising=False)
        assert tm.resolve_tenant(None, None) is None

    def test_invalid_token_degrades_to_anonymous_rather_than_raising(self, monkeypatch):
        """An expired or forged token must not 500 the request here — the route's
        own auth dependency is what returns 401."""
        import app.tenant_middleware as tm
        from app.config import settings

        monkeypatch.setattr(settings, "public_tenant_id", "default", raising=False)
        monkeypatch.setattr("app.auth._subject_of", lambda token: None)
        assert tm.resolve_tenant("garbage", None) == "default"

    def test_database_failure_degrades_to_anonymous(self, monkeypatch):
        import app.tenant_middleware as tm
        from app.config import settings

        def _boom(uid):
            raise RuntimeError("db down")

        monkeypatch.setattr(settings, "public_tenant_id", "default", raising=False)
        monkeypatch.setattr("app.auth._subject_of", lambda token: "u")
        monkeypatch.setattr(tm, "_tenant_of_user", _boom)
        assert tm.resolve_tenant("t", None) == "default"

    def test_deactivated_account_does_not_keep_its_tenant(self, monkeypatch):
        """`_tenant_of_user` filters on `is_active`, so a token issued before
        deactivation resolves to nothing and falls through to anonymous."""
        import app.tenant_middleware as tm
        from app.config import settings

        monkeypatch.setattr(settings, "public_tenant_id", "default", raising=False)
        monkeypatch.setattr("app.auth._subject_of", lambda token: "u")
        monkeypatch.setattr(tm, "_tenant_of_user", lambda uid: None)
        assert tm.resolve_tenant("t", None) == "default"

    def test_malformed_tenant_never_reaches_the_guc(self):
        """`bind_request_scope` refuses a malformed id instead of passing it on:
        in the GUC it would behave as an empty partition rather than an error."""
        from app.tenant_context import (
            bind_request_scope,
            current_tenant,
            unbind_request_scope,
        )

        tokens = bind_request_scope("Truong B/../x")
        try:
            assert current_tenant() is None
        finally:
            unbind_request_scope(tokens)

    def test_boundary_crossings_are_an_allowlist(self):
        """Every place that steps outside the tenant boundary, pinned by name.

        `system_scope` is the one construct that disables the guarantee the rest
        of the system rests on. It is legitimate for boot, Celery and operator
        CLIs — none of which have a request or a user — and for exactly one HTTP
        endpoint. A new call site appearing anywhere else is the single change
        most likely to reopen the boundary quietly, so it fails here instead.

        Adding an entry is allowed. Adding it *without noticing* is not.
        """
        import re
        from pathlib import Path

        allowed = {
            "cli/backfill_sample_owners.py",   # operator command
            "cli/verify_deployment.py",        # operator command
            "db.py",                           # boot: CSV->DB sync spans tenants
            "sot/cli.py",                      # the SOT is a cross-tenant artefact
            "worker.py",                       # every Celery task is platform work
            "routers/sot_admin.py",            # counts compared against the SOT total
            "tenant_context.py",               # the definition itself
            "tenant_admin.py",                 # acts ON tenants, not inside one
            "auth.py",                         # identity plane: precedes the tenant
            "tenant_middleware.py",            # decides the scope, so cannot need one
            "cli/verify_existing_emails.py",   # operator command
            "cli/register_legal_document.py",  # operator command
            "cli/backfill_consents.py",        # operator command
            "cli/legal_store.py",              # operator command
            "cli/backfill_usage.py",           # operator command
            # Thiết lập áp cho cả nền tảng, không thuộc tenant nào.
            "platform_settings.py",
            # Văn bản pháp lý và chấp thuận: gắn với TÀI KHOẢN, không gắn với
            # tenant. Cùng mặt phẳng danh tính với auth.py.
            "legal.py",
            # Authorisation plane. `tenant_role` answers "what is this user's
            # role in THAT tenant" — a different tenant from the caller's
            # ambient scope, so the scope cannot filter the answer. A point
            # lookup keyed by both ids; it cannot list or discover anything.
            "vocabulary_registry.py",
            # --- mặt phẳng thương mại (v4) ---
            # Hạn mức là thứ NỀN TẢNG áp lên tenant, nên nó phải đọc được số
            # liệu của tenant đang bị áp — kể cả khi người gọi là quản trị viên
            # nền tảng đứng ở một tenant khác. Cùng lý do với tenant_admin.py.
            "plans.py",
            # Gộp số đo qua MỌI tenant trong một lượt GROUP BY. Phạm vi theo
            # tenant của người phái sẽ khiến bảng gộp chỉ có một dòng.
            "usage.py",
            # Xác thực bằng khoá API xảy ra TRƯỚC khi biết tenant nào — chính
            # khoá là thứ quyết định tenant. Cùng vòng lặp nhân-quả với auth.py.
            "api_keys.py",
            # Hàng đợi giao webhook trải trên mọi tenant; tiến trình giao không
            # có yêu cầu nào để lấy phạm vi.
            "webhooks.py",
            # Xuất và xoá vĩnh viễn: người vận hành nền tảng tác động LÊN một
            # tenant, không đứng bên trong nó.
            "tenant_lifecycle.py",
            # /metrics là điểm Prometheus quét, không có người dùng nào; nó
            # tổng hợp số liệu của mọi tenant thành một trang.
            "metrics.py",
            # CHỈ hai hàm ĐỌC dùng cho giám sát: `count_since` và
            # `seconds_since_last_entry`. Chúng trả lời "sổ kiểm toán có còn lớn
            # lên không" cho toàn nền tảng, và được `/metrics` gọi — nơi không
            # có người dùng nào để lấy phạm vi.
            #
            # `record()` KHÔNG crossing và không được phép trở thành như vậy.
            # Nó cố ý fail-closed khi không có phạm vi: một dòng kiểm toán
            # không biết mình thuộc tenant nào là một dòng không ai đọc lại
            # được đúng chỗ. Xem docstring `app/audit.py`.
            #
            # Phạm vi đặt TRONG hai hàm đó chứ không ở chỗ gọi, để chúng không
            # thể bị gọi sai: gọi từ nơi thiếu phạm vi thì RLS lọc sạch và con
            # số trả về sẽ SAI trong im lặng — tệ hơn hẳn một lỗi.
            "audit.py",
            # Lệnh của người vận hành: xuất trạng thái đồng thuận của MỘT tenant
            # ra tệp cho các script offline. Chạy từ dòng lệnh, nơi không có
            # request nào đặt phạm vi.
            #
            "cli/consent_snapshot.py",
            # `access_gate.py` — CHỈ hàm `_has_any_tenant_grant`.
            #
            # Nó trả lời "tài khoản này đã từng được cấp một vai ở tầng tenant
            # chưa", và câu hỏi đó cắt ngang mọi tenant THEO ĐỊNH NGHĨA: một
            # người có thể là quản trị viên của tenant B trong khi nhà của họ ở
            # tenant A. Hỏi trong phạm vi nhà là bản đầu, và nó chặn nhầm đúng
            # ca dùng ấy — `POST /tenants/B/invitations` của một admin thật trả
            # 403.
            #
            # Middleware cũng chạy TRƯỚC khi phạm vi request được đặt, cùng lý
            # do như `auth.py`: nó là một phần của việc quyết định người gọi
            # được đi tiếp hay không.
            #
            # Hình dạng truy vấn là thứ làm việc nới phạm vi này an toàn, không
            # phải sự tin tưởng: một phép tra điểm theo `user_id` đã biết, `LIMIT
            # 1`, trả về đúng một hằng số. Nó không liệt kê được thành viên, không
            # đọc được tenant nào, và không trả lời được câu hỏi nào mà người gọi
            # chưa hỏi về chính mình.
            "access_gate.py",
            # `consent_gate.py` — CHỈ hàm cầu nối `_sync_signer_consent_inner`.
            # Nó chạy từ luồng đăng ký và từ lần đóng góp đầu tiên, tức mặt
            # phẳng danh tính, nơi người dùng có thể chưa có phạm vi tenant nào.
            # Mọi câu ghi trong đó mang `tenant_id` lấy từ chính hàng `signers`
            # của người ấy.
            #
            # Hai hàm ĐỌC (`load_consents`, `_resolve_aliases`) CỐ Ý không bọc
            # phạm vi, dù đã có `tenant_id = %s` trong SQL — hai lớp chứ không
            # một. Gọi từ nơi thiếu phạm vi thì chúng nhận 0 hàng, nghĩa là
            # "không ai có đồng thuận", nghĩa là CHẶN. Hướng hỏng đó đúng chiều:
            # thiếu phạm vi làm cổng khoá chặt hơn, không mở ra.
            "consent_gate.py",
            # Lệnh của người vận hành: chép chấp thuận đã có sẵn trong
            # `user_consents` sang `signer_consents` cho dữ liệu cũ.
            "cli/backfill_signer_consents.py",
            # Đổi tên tài khoản. Mặt phẳng DANH TÍNH, đi trước tenant — cùng lý
            # do với `auth.py`: lệnh có thể tới từ dòng lệnh, nơi không có
            # request nào đặt phạm vi, và bản thân việc đọc `users` để biết
            # tenant của người đó là bước đầu tiên.
            #
            # Bù lại việc RLS không lọc: MỌI câu UPDATE trong đó đều mang
            # `tenant_id = %s` lấy từ chính hàng `users` vừa đọc. Không có mệnh
            # đề ấy thì nhánh "hàng vô chủ, khớp theo tên hiển thị" sẽ đổi tên
            # cả dữ liệu của tenant khác trùng tên — lỗi vô hình trên bản triển
            # khai một tenant. Xem chú thích trong `rename_user`.
            "account_rename.py",
            # Vòng đời đăng ký. Lượt quét chạy từ celery-beat, nơi không có
            # request nào đặt phạm vi, và nó phải xét MỌI tenant — đó chính là
            # công việc của nó. Một lượt quét chỉ thấy tenant của chính mình là
            # một lượt quét vô nghĩa.
            #
            # Bù lại việc RLS không lọc: mọi câu ghi đều mang khoá chính
            # (`subscription_id`) hoặc `tenant_id = %s` lấy từ chính hàng vừa
            # đọc ra trong cùng lượt, chứ không từ tham số bên ngoài. Không câu
            # nào ghi theo một điều kiện do người gọi truyền vào.
            "subscription_lifecycle.py",
            # Thu hồi phiên đăng nhập. Mặt phẳng DANH TÍNH, cùng lý do với
            # `auth.py`: lệnh tới từ quản trị viên nền tảng, từ dòng lệnh, hoặc
            # từ chính đường phát hiện refresh token bị dùng lại — không đường
            # nào trong đó có phạm vi tenant của NẠN NHÂN.
            #
            # Đây không phải nới lỏng cho tiện: `users` có RLS, nên bản đầu
            # thiếu phạm vi đã làm `UPDATE ... sessions_invalid_before` khớp 0
            # dòng TRONG IM LẶNG — lệnh thu hồi phiên trông như thành công mà
            # không thu hồi gì. Câu ghi duy nhất ở đây khoá theo `id = %s` của
            # đúng một người dùng, không nhận điều kiện nào từ bên ngoài.
            "activity.py",
            # --- mặt phẳng phân quyền (PDM v1.0) ---
            # Adapter nạp policy của MỌI tenant vào một enforcer dùng chung cho
            # cả tiến trình. Một enforcer chỉ thấy tenant của người phái là một
            # enforcer không trả lời được cho ai khác. Cùng loại với `db.py`.
            "authorization/adapter.py",
            # Hai phép tra ĐIỂM, cùng lý do đã viết cho `vocabulary_registry.py`:
            # phạm vi hiện hành là tenant NHÀ của người gọi, còn câu hỏi nói về
            # tenant được NÊU TÊN trong đường dẫn — có thể là tenant khác. Lọc
            # theo phạm vi nhà sẽ luôn cho ra "không tìm thấy", tức là quản trị
            # viên nền tảng không thao tác được lên tenant nào.
            "authorization/scope_resolver.py",
            "authorization/authorization_service.py",
            # Mã hành động thuộc mặt phẳng DANH TÍNH, không phải mặt phẳng
            # tenant: bảng `user_action_passcodes` cố ý không có `tenant_id` và
            # cố ý không chịu RLS (RLS ở đó fail-OPEN — khớp 0 dòng đọc thành
            # "chưa đặt mã", tức là âm thầm BỎ QUA bước xác thực nâng cấp).
            # Cùng lý do với `auth.py`.
            "authorization/passcode.py",
            # Đọc mốc thay đổi policy trên toàn hàng sự kiện. Chạy từ một luồng
            # nền không có request nào để lấy phạm vi, và câu hỏi nó hỏi —
            # "policy có mới hơn lần nạp trước không" — là câu hỏi cấp nền tảng.
            "authorization/policy_invalidator.py",
            # Lệnh của người vận hành: dịch quyền cũ sang RBAC mới cho MỌI
            # tenant trong một lượt.
            "cli/backfill_authz.py",
            # `training_tasks.py` — CHỈ hàm `_checkpoint_owners`.
            #
            # Lượt dọn checkpoint là tác vụ hạ tầng chạy trên MỘT thư mục dùng
            # chung chứa hiện vật của mọi tổ chức. Nó phải thấy tất cả để biết
            # KHÔNG được xoá cái gì — phạm vi ở đây phục vụ việc bảo vệ chứ
            # không phải việc truy cập, và đó là điều làm nó khác mọi crossing
            # khác trong danh sách này.
            #
            # Hướng hỏng nếu bỏ phạm vi đi lại chính là hướng nguy hiểm: lượt
            # quét chỉ thấy job của một tenant, kết luận rằng checkpoint của
            # tenant khác là tệp mồ côi, rồi XOÁ chúng theo lịch. Đo được
            # 16/08/2026 (C3-S5) với bản cũ áp "giữ 20 bản mới nhất" trên cả
            # thư mục: một tổ chức train nhiều đẩy hiện vật của tổ chức khác ra
            # khỏi cửa sổ giữ.
            #
            # Hàm này chỉ ĐỌC, và trả về một ánh xạ đường-dẫn → tenant. Nó không
            # ghi gì; quyết định xoá nằm ở `_checkpoints_to_prune`, nơi cửa sổ
            # giữ được áp RIÊNG cho từng tenant.
            "training_tasks.py",
        }

        app = Path(__file__).resolve().parents[1] / "app"
        # Match a call, not the word: docstrings in tenant_context.py discuss it
        # at length and must not register as call sites.
        call = re.compile(r"^\s*(with\s+)?(enter_)?system_scope\(|^@platform_command\(", re.M)
        found = {
            str(p.relative_to(app)).replace("\\", "/")
            for p in app.rglob("*.py")
            if call.search(p.read_text(encoding="utf-8"))
        }

        assert found <= allowed, (
            f"new boundary crossing(s): {sorted(found - allowed)}. If deliberate, "
            f"add the file here with a one-line reason."
        )

    def test_no_router_crosses_the_boundary_except_the_documented_one(self):
        from pathlib import Path

        routers = Path(__file__).resolve().parents[1] / "app" / "routers"
        crossing = {
            p.name for p in routers.glob("*.py")
            if "system_scope(" in p.read_text(encoding="utf-8")
        }
        assert crossing == {"sot_admin.py"}, (
            "a request handler acting for every tenant is how the boundary gets "
            "reopened; sot_admin is the one documented exception (cross-tenant "
            "row counts compared against the published SOT)"
        )

    def test_no_header_can_choose_the_tenant(self):
        """Honouring a client-supplied `X-Tenant-Id` would make the isolation
        boundary a request field. Asserted on the signature: resolution takes
        credentials only, so there is no channel for one."""
        import inspect

        from app.tenant_middleware import resolve_tenant

        assert list(inspect.signature(resolve_tenant).parameters) == [
            "access_cookie", "bearer",
        ]


# ---------------------------------------------------------------------------
# Vùng: danh mục toàn cục KHÔNG được thành đường vòng qua cô lập tenant
# ---------------------------------------------------------------------------


class TestRegionIsNotABypass:
    """`regions` nằm NGOÀI RLS, và đó là đúng — `bac` không phải dữ liệu của ai.

    Nhưng "ngoài RLS" cộng với "ghi được" thì thành một đường vòng thật, vì
    `classes.region -> regions(code)` là ON UPDATE CASCADE: đổi một mã vùng sẽ
    ghi lại `classes` của MỌI tenant, mà lượt ghi đó không chạm bảng `classes`
    nên không policy nào của nó được hỏi tới.

    Phân biệt phải giữ cho rõ: DỮ LIỆU THAM CHIẾU TOÀN CỤC không phải DỮ LIỆU
    TENANT DÙNG CHUNG. Cái trước đọc chung được; cái sau thì không bao giờ.
    """

    def test_the_app_role_can_read_the_catalogue(self, app_conn):
        cur = _scoped(app_conn, TENANT_A)
        cur.execute("SELECT code FROM regions ORDER BY sort_order")
        codes = [r[0] for r in cur.fetchall()]
        app_conn.rollback()
        # `unclassified` và `common` phải là HAI mã khác nhau: cái đầu nghĩa là
        # chưa ai xác minh, cái sau nghĩa là đã xác minh không cần phân vùng.
        assert {"unclassified", "common", "bac", "trung", "nam"} <= set(codes)

    @pytest.mark.parametrize("sql, params", [
        ("INSERT INTO regions(code, name_vi) VALUES ('xx', 'X')", ()),
        ("UPDATE regions SET code = 'bac2' WHERE code = 'bac'", ()),
        ("DELETE FROM regions WHERE code = 'common'", ()),
    ])
    def test_the_app_role_cannot_write_the_catalogue(self, app_conn, sql, params):
        """Sửa danh mục là việc của vai migration, không phải của ứng dụng.

        `UPDATE` là câu nguy hiểm nhất trong ba câu: nhờ ON UPDATE CASCADE, một
        lượt đổi mã vùng ghi lại lớp của mọi tenant cùng lúc.
        """
        cur = _scoped(app_conn, TENANT_A)
        with pytest.raises(psycopg2.errors.InsufficientPrivilege):
            cur.execute(sql, params)
        app_conn.rollback()

    def test_a_tenant_cannot_confirm_another_tenants_class_exists(self, app_conn):
        """0 hàng, KHÔNG phải "403 lớp này của tenant khác".

        Một câu trả lời phân biệt được "không tồn tại" với "tồn tại nhưng của
        người khác" đã rò rỉ chính thứ cần giấu. Tầng HTTP phải dịch 0 hàng
        thành 404 chứ không phải 403.
        """
        cur = _scoped(app_conn, TENANT_A)
        cur.execute(
            "SELECT class_uid FROM classes WHERE class_uid = %s", (f"cls-{TENANT_B}",))
        assert cur.fetchall() == []
        app_conn.rollback()

    def test_reclassifying_another_tenants_class_touches_nothing(self, app_conn):
        """Đúng hình dạng của `reclassify_class_region`, nhưng bỏ mọi lớp lọc ở
        tầng ứng dụng — còn lại một mình policy."""
        cur = _scoped(app_conn, TENANT_A)
        cur.execute(
            "UPDATE classes SET region = 'bac' WHERE class_uid = %s",
            (f"cls-{TENANT_B}",))
        assert cur.rowcount == 0
        app_conn.commit()

        check = _scoped(app_conn, TENANT_B)
        check.execute(
            "SELECT region FROM classes WHERE class_uid = %s", (f"cls-{TENANT_B}",))
        assert check.fetchone()[0] != "bac"
        app_conn.rollback()

    def test_a_tenant_cannot_write_a_row_into_another_tenant(self, app_conn):
        """`WITH CHECK`, không phải `USING`. Nhiều hệ thống chỉ kiểm đường ĐỌC
        rồi quên đường GHI, và khi đó một tenant đẩy được hàng sang tenant khác
        dù không đọc nổi hàng nào của họ."""
        cur = _scoped(app_conn, TENANT_A)
        with pytest.raises(psycopg2.errors.Error):
            cur.execute(
                "INSERT INTO classes(class_uid, tenant_id, slug, language, region) "
                "VALUES ('cls-smuggled', %s, 'smuggled', 'vn', 'bac')",
                (TENANT_B,))
        app_conn.rollback()

    def test_a_tenant_cannot_move_its_own_row_to_another_tenant(self, app_conn):
        """Đường thoát kín đáo hơn: hàng hợp lệ lúc đọc, nhưng bị đẩy sang tenant
        khác lúc ghi. `WITH CHECK` phải xét giá trị MỚI, không phải giá trị cũ."""
        cur = _scoped(app_conn, TENANT_A)
        with pytest.raises(psycopg2.errors.Error):
            cur.execute(
                "UPDATE classes SET tenant_id = %s WHERE class_uid = %s",
                (TENANT_B, f"cls-{TENANT_A}"))
        app_conn.rollback()
