apiVersion: 1

contactPoints:
  - orgId: 1
    name: "Admin Email"
    receivers:
      - uid: admin-email-receiver
        type: email
        settings:
          addresses: minhb2203567@student.ctu.edu.vn
          singleEmail: true
          subject: '{{ template "email.voya.subject" . }}'
          message: '{{ template "email.voya.message" . }}'
