"""initial schema v2 - 37 tables (ERD v2)

Revision ID: af7fe2a719fc
Revises: 
Create Date: 2026-07-04 13:01:12.087677

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'af7fe2a719fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('languages',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('log_categories',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('retention_days', sa.Integer(), server_default=sa.text('30'), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('model_architectures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_type', sa.String(length=64), nullable=True),
    sa.Column('default_hyperparams', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trainer_entrypoint', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('roles',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sign_features',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('requires_two_hands', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('requires_face_expression', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('requires_body_movement', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dialects',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('language_code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('system_log_files',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('category_code', sa.String(length=32), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('local_file_path', sa.Text(), nullable=True),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['category_code'], ['log_categories.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('role_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('classes',
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('class_uid', sa.Text(), nullable=False),
    sa.Column('dialect_code', sa.String(length=16), nullable=False),
    sa.Column('feature_id', sa.Integer(), nullable=True),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('label_original', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['dialect_code'], ['dialects.code'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['feature_id'], ['sign_features.id'], ),
    sa.PrimaryKeyConstraint('class_uid'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('devices',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('browser_info', sa.Text(), nullable=True),
    sa.Column('os_info', sa.Text(), nullable=True),
    sa.Column('camera_specs', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('legal_documents',
    sa.Column('document_code', sa.String(length=64), nullable=False),
    sa.Column('document_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('content_url', sa.Text(), nullable=False),
    sa.Column('content_checksum', sa.String(length=64), nullable=True),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('published_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('document_code')
    )
    op.create_index(op.f('ix_legal_documents_document_type'), 'legal_documents', ['document_type'], unique=False)
    op.create_index('uq_legal_active_per_type', 'legal_documents', ['document_type'], unique=True, postgresql_where=sa.text('is_active'))
    op.create_table('user_profiles',
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('yob', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_sessions',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('device_info', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token_hash')
    )
    op.create_table('workspaces',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('owner_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('visibility', sa.String(length=16), server_default=sa.text("'private'"), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('class_categories',
    sa.Column('class_uid', sa.Text(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['class_uid'], ['classes.class_uid'], ),
    sa.PrimaryKeyConstraint('class_uid', 'category_id')
    )
    op.create_table('projects',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('owner_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('visibility', sa.String(length=16), server_default=sa.text("'private'"), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_workspace_id'), 'projects', ['workspace_id'], unique=False)
    op.create_table('system_audit_logs',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('workspace_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.String(length=128), nullable=True),
    sa.Column('old_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_audit_logs_created_at'), 'system_audit_logs', ['created_at'], unique=False)
    op.create_table('user_consents',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('document_code', sa.String(length=64), nullable=False),
    sa.Column('is_agreed', sa.Boolean(), nullable=False),
    sa.Column('consent_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('agreed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['document_code'], ['legal_documents.document_code'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_consents_user_id'), 'user_consents', ['user_id'], unique=False)
    op.create_table('workspace_members',
    sa.Column('workspace_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('workspace_id', 'user_id')
    )
    op.create_table('workspace_quotas',
    sa.Column('workspace_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('storage_quota_mb', sa.Integer(), server_default=sa.text('5120'), nullable=False),
    sa.Column('storage_used_mb', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_projects', sa.Integer(), server_default=sa.text('10'), nullable=False),
    sa.Column('max_members', sa.Integer(), server_default=sa.text('20'), nullable=False),
    sa.Column('max_concurrent_trainings', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('gpu_minutes_quota', sa.Integer(), server_default=sa.text('600'), nullable=False),
    sa.Column('gpu_minutes_used', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('workspace_id')
    )
    op.create_table('collection_sessions',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('session_uid', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('class_uid', sa.Text(), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('device_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('snapshot_dialect_code', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'in_progress'"), nullable=False),
    sa.ForeignKeyConstraint(['class_uid'], ['classes.class_uid'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('session_uid')
    )
    op.create_index('ix_collection_sessions_status_created', 'collection_sessions', ['status', 'created_at'], unique=False)
    op.create_table('datasets',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('visibility', sa.String(length=16), server_default=sa.text("'private'"), nullable=False),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'slug', name='uq_datasets_project_slug')
    )
    op.create_index(op.f('ix_datasets_workspace_id'), 'datasets', ['workspace_id'], unique=False)
    op.create_table('models',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('architecture_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.CheckConstraint("source != 'platform' OR architecture_id IS NOT NULL", name='ck_models_platform_needs_architecture'),
    sa.ForeignKeyConstraint(['architecture_id'], ['model_architectures.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'slug', name='uq_models_project_slug')
    )
    op.create_index(op.f('ix_models_workspace_id'), 'models', ['workspace_id'], unique=False)
    op.create_table('project_classes',
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('class_uid', sa.Text(), nullable=False),
    sa.Column('custom_instructions', sa.Text(), nullable=True),
    sa.Column('target_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_uid'], ['classes.class_uid'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'class_uid')
    )
    op.create_table('project_members',
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('project_role', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'user_id')
    )
    op.create_table('project_sheet_exports',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('export_target', sa.String(length=16), nullable=False),
    sa.Column('current_spreadsheet_id', sa.String(length=128), nullable=True),
    sa.Column('snapshot_file_path', sa.Text(), nullable=True),
    sa.Column('last_exported_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_sheet_exports_export_target'), 'project_sheet_exports', ['export_target'], unique=False)
    op.create_table('dataset_versions',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('dataset_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('manifest_file_path', sa.Text(), nullable=True),
    sa.Column('manifest_checksum', sa.String(length=64), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=True),
    sa.Column('split_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('size_mb', sa.Integer(), nullable=True),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('frozen_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'version_number', name='uq_dataset_versions_number')
    )
    op.create_table('raw_uploads',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('upload_uid', sa.Text(), nullable=False),
    sa.Column('session_uid', sa.String(length=64), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=True),
    sa.Column('local_path', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'pending'"), nullable=False),
    sa.ForeignKeyConstraint(['session_uid'], ['collection_sessions.session_uid'], ),
    sa.PrimaryKeyConstraint('upload_uid')
    )
    op.create_table('samples',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sample_uid', sa.Text(), nullable=False),
    sa.Column('session_uid', sa.String(length=64), nullable=False),
    sa.Column('upload_uid', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'pending'"), nullable=False),
    sa.ForeignKeyConstraint(['session_uid'], ['collection_sessions.session_uid'], ),
    sa.ForeignKeyConstraint(['upload_uid'], ['raw_uploads.upload_uid'], ),
    sa.PrimaryKeyConstraint('sample_uid')
    )
    op.create_table('training_jobs',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('model_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('dataset_version_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('architecture_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('hyperparams', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('progress', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('celery_task_id', sa.String(length=64), nullable=True),
    sa.Column('log_file_path', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('submitted_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['architecture_id'], ['model_architectures.id'], ),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_training_jobs_status_created', 'training_jobs', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_training_jobs_workspace_id'), 'training_jobs', ['workspace_id'], unique=False)
    op.create_table('model_versions',
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('model_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('training_job_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('dataset_version_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('weights_path', sa.Text(), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=True),
    sa.Column('metadata_file_path', sa.Text(), nullable=True),
    sa.Column('size_mb', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['training_job_id'], ['training_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id', 'version', name='uq_model_versions_version'),
    sa.UniqueConstraint('training_job_id')
    )
    op.create_table('sample_media',
    sa.Column('sample_uid', sa.Text(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('storage_url', sa.Text(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('fps_original', sa.Float(), nullable=True),
    sa.Column('seq_len', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sample_uid'], ['samples.sample_uid'], ),
    sa.PrimaryKeyConstraint('sample_uid'),
    sa.UniqueConstraint('checksum')
    )
    op.create_table('sample_processing',
    sa.Column('sample_uid', sa.Text(), nullable=False),
    sa.Column('processing_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'processing'"), nullable=False),
    sa.Column('result_file_path', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sample_uid'], ['samples.sample_uid'], ),
    sa.PrimaryKeyConstraint('sample_uid', 'processing_type')
    )
    op.create_table('sample_reviews',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('sample_uid', sa.Text(), nullable=False),
    sa.Column('reviewer_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('suggested_class_uid', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sample_uid'], ['samples.sample_uid'], ),
    sa.ForeignKeyConstraint(['suggested_class_uid'], ['classes.class_uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sample_sync_status',
    sa.Column('sample_uid', sa.Text(), nullable=False),
    sa.Column('gdrive_synced', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['sample_uid'], ['samples.sample_uid'], ),
    sa.PrimaryKeyConstraint('sample_uid')
    )
    op.create_table('inference_logs',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('model_version_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('sample_uid', sa.Text(), nullable=False),
    sa.Column('is_hard_example', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('log_file_path', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['sample_uid'], ['samples.sample_uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inference_logs')
    op.drop_table('sample_sync_status')
    op.drop_table('sample_reviews')
    op.drop_table('sample_processing')
    op.drop_table('sample_media')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_training_jobs_workspace_id'), table_name='training_jobs')
    op.drop_index('ix_training_jobs_status_created', table_name='training_jobs')
    op.drop_table('training_jobs')
    op.drop_table('samples')
    op.drop_table('raw_uploads')
    op.drop_table('dataset_versions')
    op.drop_index(op.f('ix_project_sheet_exports_export_target'), table_name='project_sheet_exports')
    op.drop_table('project_sheet_exports')
    op.drop_table('project_members')
    op.drop_table('project_classes')
    op.drop_index(op.f('ix_models_workspace_id'), table_name='models')
    op.drop_table('models')
    op.drop_index(op.f('ix_datasets_workspace_id'), table_name='datasets')
    op.drop_table('datasets')
    op.drop_index('ix_collection_sessions_status_created', table_name='collection_sessions')
    op.drop_table('collection_sessions')
    op.drop_table('workspace_quotas')
    op.drop_table('workspace_members')
    op.drop_index(op.f('ix_user_consents_user_id'), table_name='user_consents')
    op.drop_table('user_consents')
    op.drop_index(op.f('ix_system_audit_logs_created_at'), table_name='system_audit_logs')
    op.drop_table('system_audit_logs')
    op.drop_index(op.f('ix_projects_workspace_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('class_categories')
    op.drop_table('workspaces')
    op.drop_table('user_sessions')
    op.drop_table('user_profiles')
    op.drop_index('uq_legal_active_per_type', table_name='legal_documents', postgresql_where=sa.text('is_active'))
    op.drop_index(op.f('ix_legal_documents_document_type'), table_name='legal_documents')
    op.drop_table('legal_documents')
    op.drop_table('devices')
    op.drop_table('classes')
    op.drop_table('users')
    op.drop_table('system_log_files')
    op.drop_table('dialects')
    op.drop_table('sign_features')
    op.drop_table('roles')
    op.drop_table('model_architectures')
    op.drop_table('log_categories')
    op.drop_table('languages')
    op.drop_table('categories')
    # ### end Alembic commands ###
